backend:
  name: git-gateway
  branch: main # Of 'master' afhankelijk van je GitHub branch

media_folder: "assets/images/cars" # Waar de foto's worden opgeslagen
public_folder: "/assets/images/cars"

collections:
  - name: "occasions"
    label: "Auto's"
    folder: "content/occasions" # Waar de data van elke auto wordt opgeslagen
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Merk en Model", name: "title", widget: "string"}
      - {label: "Prijs", name: "price", widget: "string"}
      - {label: "Bouwjaar", name: "year", widget: "number"}
      - {label: "Kilometerstand", name: "km", widget: "string"}
      - {label: "Brandstof", name: "fuel", widget: "select", options: ["Benzine", "Diesel", "Hybride", "Elektrisch"]}
      - {label: "Hoofdfoto", name: "image", widget: "image"}
      - {label: "Extra Foto's", name: "gallery", widget: "list", field: {label: "Foto", name: "img", widget: "image"}}
      - {label: "Beschrijving", name: "body", widget: "markdown"}